name: wob
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  get: ^4.6.1
  shared_preferences: ^2.0.12
  google_fonts: ^2.2.0
  pin_code_fields: ^7.3.0
  avatar_glow: ^2.0.2
  flutter_switch: ^0.3.2
  bulleted_list: ^0.0.1+0.1a
  flutter_keyboard_visibility: ^5.1.0
  flutter_beacon: ^0.5.1
  permission_handler: ^8.3.0
  google_maps_flutter: ^2.1.2
  location: ^4.3.0
  clippy_flutter: ^2.0.0-nullsafety.1
  intl: ^0.17.0
  url_launcher: ^6.0.20
  flutter_fortune_wheel: ^1.2.0
  scroll_date_picker: ^3.6.0
  bordered_text: ^2.0.0
  barcode: ^2.2.3
  flutter_svg: ^1.1.6
  screen_brightness: ^0.2.2
  extended_sliver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/slots/
    - assets/brands/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-BoldItalic.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-MediumItalic.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
        - asset: assets/fonts/Gilroy-SemiBold.ttf
        - asset: assets/fonts/Gilroy-SemiBoldItalic.ttf
    - family: Super Retro M54
      fonts:
        - asset: assets/fonts/Super-Retro-M54.ttf